kubeflow/pytorch-operator

- README.md
- Adds a link to the proposal so that we know the goals for the repo and so that the design is up to date with community discussion.
> Provide link to the proposal

- README.md
- examples/pytorchjob.yaml
- vendor/k8s.io/code-generator/generate-groups.sh
- Renames the PyTorchJob example to pytorchjob.yaml
- Removes a debugging line added in the vendor
- Removes a binary that was commited by accident
> Minor cleanup

- Dockerfile
- prow_config.yaml
- pytorch-operator-chart/templates/deployment.yaml
- scripts/build.sh
- scripts/create-cluster.sh
- scripts/delete-cluster.sh
- scripts/run-tests.sh
- test/e2e/main.go
- test/workflows/components/workflows.libsonnet
- Makes changes to the argo workflow for e2e
- Fixes operator deployment quoting issue
- Adds infrastructure scripts for:
- Creating a cluster
- Deleting a cluster
- Building a container
- Running tests
- Adds a simple e2e test in golang
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pytorch-operator/14)
> Adds simple e2e

- OWNERS
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pytorch-operator/15)
> Adding approver

- .travis.yml
- linter_config.json
- pkg/trainer/replicas_test.go
Adding back in the travis and lint tests. May need to enable travis for this repo
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pytorch-operator/10)
> Add in travis and lint tests

- README.md
- examples/pytorchjob.yaml
- pkg/trainer/replicas.go
- pkg/trainer/replicas_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pytorch-operator/21)
> Unbuffered python for realtime logs

- test/workflows/components/workflows.libsonnet
Related https://github.com/kubeflow/testing/issues/90
/cc @gaocegege @jose5918
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pytorch-operator/31)
> Move away from mlkube-testing to kubeflow-ci

- releasing.md
- submit_release_job.sh
- test/workflows/environments/releasing/params.libsonnet
Adding some releasing instructions. Not sure who has permissions to test this, but it should be similar release process to tf-operator 
@ankushagarwal 
@jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pytorch-operator/28)
> Add releasing instructions

- OWNERS
Adding to owners file
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pytorch-operator/46)
> Adding to owners

- scripts/run-tests.sh
- test/workflows/components/workflows.libsonnet
Since ksonnet is recommended way to install, test scripts should use ksonnet way of installation of pytorch operator
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pytorch-operator/44)
> Changing from helm to ksonnet install

- linter_config.json
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pytorch-operator/53)
> linter: Rename gas to gosec

- Gopkg.lock
- pkg/controller.v2/pytorch/job.go
- pkg/controller.v2/pytorch/pod.go
- vendor/github.com/kubeflow/tf-operator/pkg/controller.v2/jobcontroller/pod.go
- vendor/github.com/kubeflow/tf-operator/pkg/logger/logger.go
Minor log improvements
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pytorch-operator/57)
> log improvements

- Gopkg.lock
- pkg/controller.v2/pytorch/controller.go
- pkg/controller.v2/pytorch/controller_test.go
- pkg/controller.v2/pytorch/pod.go
- vendor/github.com/kubeflow/tf-operator/pkg/controller.v2/jobcontroller/jobcontroller.go
Minor changes are added to make compatible with the upstream controller interface.  Controller package is updated with dep
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pytorch-operator/62)
> Compatibility with upstream controller changes

- pkg/apis/pytorch/v1alpha2/types.go
- pkg/controller.v2/pytorch/pod.go
- pkg/controller.v2/pytorch/status.go
Porting minor changes from TF controller
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pytorch-operator/63)
> Porting minor fixes from TF

- Gopkg.lock
- cmd/pytorch-operator.v2/app/server.go
- vendor/github.com/kubeflow/tf-operator/pkg/controller.v2/jobcontroller/pod.go
See https://github.com/kubeflow/tf-operator/pull/821
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pytorch-operator/64)
> Adding corev1 scheme to Events

- .travis.yml
- Gopkg.lock
Pytorch operator v1alpha2 build is added to travis
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pytorch-operator/72)
> Build check added to travis

- examples/gloo/Dockerfile
- examples/gloo/dist_mnist.py
- examples/gloo/v1alpha2/pytorch_job_mnist.yaml
Example without workflows
Fixes https://github.com/kubeflow/pytorch-operator/issues/67, but master restarts after worker complete.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pytorch-operator/74)
> Gloo support added

- Gopkg.lock
- vendor/github.com/kubeflow/tf-operator/pkg/common/jobcontroller/jobcontroller.go
- vendor/github.com/kubeflow/tf-operator/pkg/common/jobcontroller/pod.go
- vendor/github.com/kubeflow/tf-operator/pkg/common/jobcontroller/service.go
- vendor/github.com/kubeflow/tf-operator/pkg/common/jobcontroller/util.go
Pull latest changes from the common JobController package needed for v1beta1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pytorch-operator/95)
> Updating common JobController vendor

- .travis.yml
- cmd/pytorch-operator.v1beta1/app/options/options.go
- cmd/pytorch-operator.v1beta1/app/server.go
- cmd/pytorch-operator.v1beta1/main.go
- pkg/common/util/testutil/const.go
- pkg/common/util/testutil/job.go
- pkg/common/util/testutil/pod.go
- pkg/common/util/testutil/service.go
- pkg/common/util/testutil/util.go
- pkg/common/util/unstructured/informer.go
- pkg/controller.v1beta1/pytorch/controller.go
- pkg/controller.v1beta1/pytorch/controller_test.go
- pkg/controller.v1beta1/pytorch/informer.go
- pkg/controller.v1beta1/pytorch/job.go
- pkg/controller.v1beta1/pytorch/job_test.go
- pkg/controller.v1beta1/pytorch/pod.go
- pkg/controller.v1beta1/pytorch/pod_test.go
- pkg/controller.v1beta1/pytorch/service.go
- pkg/controller.v1beta1/pytorch/service_test.go
- pkg/controller.v1beta1/pytorch/status.go
- pkg/controller.v1beta1/pytorch/status_test.go
- pkg/controller.v1beta1/pytorch/util.go
- pkg/controller.v1beta1/pytorch/util_test.go
Controller is added for v1beta1 api.  The testutil and unstructured folder will be restructured when older versions are deleted.
Fixes #96
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pytorch-operator/97)
> Adding controller for v1beta1 api

- examples/ddp/mnist/cpu/v1beta1/job_mnist_ddp_cpu.yaml
- examples/ddp/mnist/gpu/v1beta1/job_mnist_ddp_gpu.yaml
- examples/gloo-dist/mnist/v1beta1/pytorch_job_mnist.yaml
- examples/mpi-dist/mnist/cpu/v1beta1/mpi_mnist_job_cpu.yaml
- examples/mpi-dist/mnist/gpu/v1beta1/mpi_mnist_job_gpu.yaml
- examples/smoke-dist/v1beta1/pytorch_job_sendrecv.yaml
- examples/tcp-dist/cifar10/v1beta1/pytorch_job_cifar.yaml
- examples/tcp-dist/mnist/v1beta1/pytorch_job_mnist.yaml
Adapted examples for v1beta1 api
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pytorch-operator/98)
> Adding examples for v1beta1 API

- prow_config.yaml
Adding image to kubeflow-images-public repo during postsubmit
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pytorch-operator/100)
> Release image to kubeflow images public

- prow_config.yaml
- test/workflows/components/workflows.libsonnet
Registry in the params are not overriden for the argo steps
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pytorch-operator/102)
> Fix registry override for image builds

- scripts/v1alpha2/delete-v1alpha2.sh
- scripts/v1beta1/delete-v1beta1.sh
- scripts/v1beta1/run-cleanpodpolicy-all.sh
- scripts/v1beta1/run-defaults.sh
- scripts/v1beta1/setup-v1beta1.sh
- test/e2e/v1beta1/cleanpolicy_all.go
- test/e2e/v1beta1/defaults.go
- test/workflows/components/workflows.libsonnet
Adding e2e tests for v1beta1
Fixes #86 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pytorch-operator/101)
> Adding e2e tests for v1beta1

- .travis.yml
- cmd/pytorch-operator.v1beta1/app/server.go
- cmd/pytorch-operator.v2/app/server.go
- linter_config.json
- pkg/apis/pytorch/v1alpha2/defaults.go
- pkg/apis/pytorch/v1beta1/defaults.go
- pkg/controller.v1beta1/pytorch/controller.go
- pkg/controller.v1beta1/pytorch/informer.go
- pkg/controller.v1beta1/pytorch/pod.go
- pkg/controller.v1beta1/pytorch/service.go
- pkg/controller.v1beta1/pytorch/status.go
- pkg/controller.v1beta1/pytorch/util.go
- pkg/controller.v2/pytorch/controller.go
- pkg/controller.v2/pytorch/informer.go
- pkg/controller.v2/pytorch/pod.go
- pkg/controller.v2/pytorch/service.go
- pkg/controller.v2/pytorch/status.go
- pkg/controller.v2/pytorch/util.go
Remove gosimple as it is deprecated
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pytorch-operator/131)
> Travis build fix

- .gitignore
- pkg/controller.v1beta1/pytorch/pod.go
- pkg/controller.v1beta1/pytorch/status.go
- pkg/controller.v1beta1/pytorch/status_test.go
Related to https://github.com/kubeflow/tf-operator/pull/910
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pytorch-operator/133)
> Adding detailed events/messages to PyTorch Jobs

- pkg/apis/pytorch/v1beta2/types.go
- pkg/client/clientset/versioned/typed/pytorch/v1beta2/fake/fake_pytorchjob.go
- pkg/client/clientset/versioned/typed/pytorch/v1beta2/pytorchjob.go
- pkg/controller.v1beta2/pytorch/job.go
- pkg/controller.v1beta2/pytorch/status.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pytorch-operator/139)
> Adding status subresource

- scripts/create-cluster.sh
I changed cluster version from 1.10 to 1.11 to fix test problems. 
/assign @johnugeorge
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pytorch-operator/142)
> Change cluster version to 1.11

- examples/mnist/README.md
- examples/mnist/v1beta2/pytorch_job_mnist_gloo.yaml
- examples/mnist/v1beta2/pytorch_job_mnist_mpi.yaml
- examples/mnist/v1beta2/pytorch_job_mnist_nccl.yaml
- examples/smoke-dist/v1beta2/pytorch_job_sendrecv.yaml
- scripts/build.sh
- scripts/v1beta1/run-cleanpodpolicy-all.sh
- scripts/v1beta1/run-defaults.sh
- scripts/v1beta2/delete-v1beta2.sh
- scripts/v1beta2/run-cleanpodpolicy-all.sh
- scripts/v1beta2/run-defaults.sh
- scripts/v1beta2/setup-v1beta2.sh
- test/e2e/v1beta2/cleanpolicy_all.go
- test/e2e/v1beta2/defaults.go
- test/workflows/components/workflows.libsonnet
Testing infra code #127  has to be updated once this is merged
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pytorch-operator/143)
> Adding tests for v1beta2

- pkg/controller.v1beta2/pytorch/pod.go
Porting changes from https://github.com/kubeflow/tf-operator/pull/957
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pytorch-operator/149)
> Use kube-batch as scheduler by default when gang-scheduling is enabled

- OWNERS
Owners file is pruned so that right reviewers are notified.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pytorch-operator/157)
> Prune owners file

- pkg/apis/pytorch/validation/validation.go
- pkg/apis/pytorch/validation/validation_test.go
- pkg/controller.v1beta1/pytorch/controller.go
- pkg/controller.v1beta2/pytorch/controller.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pytorch-operator/155)
> Minor format changes

- Gopkg.lock
- Gopkg.toml
Common repo is not sourced as it is not ready yet
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pytorch-operator/156)
> Set tf operator version to v0.5.0

- pkg/controller.v1beta2/pytorch/controller.go
ref https://github.com/kubeflow/tf-operator/issues/994
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pytorch-operator/158)
> set CompletionTime first when pytorchjob exceeds limit

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pytorch-operator/159)
> Revise API version to v1beta2

- README.md
- examples/mnist/v1/pytorch_job_mnist_gloo.yaml
- examples/mnist/v1/pytorch_job_mnist_mpi.yaml
- examples/mnist/v1/pytorch_job_mnist_nccl.yaml
> Adding examples for v1 api

- pkg/apis/pytorch/v1/types.go
Similar to https://github.com/kubeflow/tf-operator/pull/1009.
> Polish documentation for PyTorch V1

- pkg/controller.v1/pytorch/controller.go
- pkg/controller.v1beta2/pytorch/controller.go
Related: https://github.com/kubernetes/kubernetes/pull/77647
> Check pending status for pastBackoffLimitOnFailure

- Gopkg.lock
- Gopkg.toml
- pkg/controller.v1/pytorch/controller.go
- pkg/controller.v1beta2/pytorch/controller.go
- vendor/github.com/kubeflow/tf-operator/pkg/apis/common/v1/openapi_generated.go
- vendor/github.com/kubeflow/tf-operator/pkg/apis/common/v1/types.go
- vendor/github.com/kubeflow/tf-operator/pkg/common/jobcontroller/jobcontroller.go
- vendor/github.com/kubeflow/tf-operator/pkg/common/jobcontroller/pod.go
Porting fix from  https://github.com/kubeflow/tf-operator/pull/1012
> Sync PodGroup fix

- Dockerfile
Moved base image from dev preview to GA
Related: https://github.com/kubeflow/tf-operator/pull/1023
> Update image base to UBI8 GA

- pkg/apis/pytorch/v1/defaults.go
- pkg/apis/pytorch/v1/types.go
- pkg/apis/pytorch/v1beta2/defaults.go
- pkg/apis/pytorch/v1beta2/types.go
> fix: Fix the comments

- docs/monitoring/README.md
- pkg/controller.v1/pytorch/controller.go
- pkg/controller.v1/pytorch/job.go
- pkg/controller.v1/pytorch/status.go
Signed-off-by: yeya24 <yb532204897@gmail.com>
Mirror PR for tf-operator : https://github.com/kubeflow/tf-operator/pull/1055
> add total suffix in counter metrics

- manifests/deployment.yaml
- manifests/rbac.yaml
- manifests/service.yaml
Update manifest to latest, making easy to test or develop pytorch-operator
> Update manifest to v0.6.0

- examples/mnist/Dockerfile.ppc64le
- examples/mnist/README.md
/cc @jinchihe @hougangliu 
I corrected the username issue. Please help to review this request. thanks.
> add mnist example dockerfile for ppc64le

- .travis.yml
- pkg/controller.v1/pytorch/job_test.go
- pkg/controller.v1/pytorch/pod_test.go
- pkg/controller.v1/pytorch/service_test.go
- scripts/v1/run-cleanpodpolicy-all.sh
- scripts/v1/run-defaults.sh
- test/e2e/v1/cleanpolicy/cleanpolicy_all.go
- test/e2e/v1/default/defaults.go
> feat: Use golanglint

- Gopkg.lock
- Gopkg.toml
- pkg/controller.v1/pytorch/util.go
- vendor/github.com/kubernetes-sigs/yaml/LICENSE
- vendor/github.com/kubernetes-sigs/yaml/fields.go
- vendor/github.com/kubernetes-sigs/yaml/yaml.go
- vendor/github.com/kubernetes-sigs/yaml/yaml_go110.go
fixed [issues-236](https://github.com/kubeflow/pytorch-operator/issues/236)
> replace gopkg.in/yaml.v2 with github.com/kubernetes-sigs/yaml repo

- pkg/common/config/config.go
> fix: Add resource limits for init container

- cmd/pytorch-operator.v1/app/options/options.go
- pkg/common/config/config.go
- pkg/controller.v1/pytorch/controller.go
- pkg/controller.v1/pytorch/pod.go
- pkg/controller.v1/pytorch/util.go
- pkg/controller.v1/pytorch/util_test.go
Fix #261 
```
-init-container-image string
The image of the injected init container, will overwrite the value in config (default "alpine:3.10")
```
> feat(init_container): Add init container image CLI argument

- README.md
https://github.com/kubeflow/kubeflow/blob/master/kubeflow/pytorch-job/pytorch-operator.libsonnet#L11 not work
> Update CRD link

- examples/bert/Dockerfile
- examples/bert/README.md
- examples/bert/bert.py
- examples/bert/pytorch_job_bert.yaml
Added Bert example with PyTorch Lightning. 
- Fixes   #334
> Bert example with Pytorch Lightning
