kubeflow/pytorch-operator

- .gcloudignore
- Adds a gcloudignore files so that vendor doesn't need to be uploaded on container builds
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pytorch-operator/19)
> Add gcloudignore

- test/workflows/environments/releasing/params.libsonnet
Related to kubeflow/kubeflow#534
/cc elsonrodriguez
/cc jose5918
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pytorch-operator/27)
> Replace kubeflow-images-staging with kubeflow-images-public

- examples/mnist/configmap.yaml
With the latest pytorch, Dataloader argument batch size has to be an integer.
Also, usage of indexing 0-dim Tensor is deprecated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pytorch-operator/36)
> Distributed mnist example fails to run

- build_image.sh
Fixes #20
Build_image.sh file is required for building image during nightly
release workflow
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pytorch-operator/39)
> Adding build_image.sh file for nightly releases

- build_image.sh
GOPath has to be exported to be picked up by the go build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pytorch-operator/41)
> Minor fix to export the GOPATH variable

- examples/dist-mnist/Makefile
- examples/dist-mnist/pytorch_job_mnist.yaml
* Create a Makefile to push the example container.
* Update the example config to reference the new image.
Fix #47
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pytorch-operator/48)
> Push the mnist example container to our examples repository.

- examples/dist-mnist/pytorch_job_mnist.yaml
Updating the example to use the available image at 
https://console.cloud.google.com/gcr/images/kubeflow-examples/GLOBAL/pytorch-dist-mnist
At the moment the image cannot be found and results in the pod being unable to start.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pytorch-operator/51)
> Incorrect tag used with pytorch_job_mnist.yaml example

- cmd/pytorch-operator.v2/app/options/options.go
- cmd/pytorch-operator.v2/app/server.go
- pkg/controller.v2/pytorch/controller_test.go
- pkg/controller.v2/pytorch/informer.go
Fixes #58 
Namespace can be given as an extra option to restrict the monitoring to namespace scope instead of the default cluster scope.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pytorch-operator/61)
> Adding option for restricting operator scope to namespace level

- cmd/pytorch-operator/app/server.go
- pkg/controller.v2/pytorch/job.go
- pkg/trainer/replicas.go
- vendor/github.com/kubeflow/tf-operator/pkg/util/k8sutil/client.go
- vendor/github.com/kubeflow/tf-operator/pkg/util/k8sutil/k8sutil.go
See https://github.com/kubeflow/tf-operator/pull/815
Also, k8sutil pkg is imported from tf-operator
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pytorch-operator/71)
> Mark Job failed when spec is invalid

- examples/gloo-dist/mnist/Dockerfile
- examples/gloo-dist/mnist/dist_mnist.py
- examples/smoke-dist/Dockerfile
- examples/tcp-dist/mnist/Dockerfile
- examples/tcp-dist/mnist/dist_mnist.py
Adding pytorch 0.4 as the base image for all examples
Fixes #69 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pytorch-operator/79)
> Adding pytorch 0.4 as default

- examples/tcp-dist/cifar10/v1alpha1/pytorch_job_cifar.yaml
The commit removed unnecessary char to fix incorrect format.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pytorch-operator/83)
> Remove unnecessary char

- pkg/apis/pytorch/validation/validation.go
- pkg/apis/pytorch/validation/validation_test.go
Adding validation tests for v1beta1 apis
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pytorch-operator/94)
> Validation test for V1beta1 apis

- prow_config.yaml
Default project is Kubeflow-ci for presubmit and post submit
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pytorch-operator/106)
> Keeping default project as kubeflow-ci

- Gopkg.lock
- Gopkg.toml
- vendor/k8s.io/api/core/v1/types.go
- vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
- vendor/k8s.io/apimachinery/pkg/runtime/serializer/json/json.go
- vendor/k8s.io/apimachinery/pkg/util/net/http.go
Ref https://github.com/kubeflow/tf-operator/pull/872
Using version allows us to be compatible with more versions.
/cc @zjj2wry 
/assign @johnugeorge
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pytorch-operator/107)
> gopkg: Use version instead of branch

- examples/katib/Dockerfile
- examples/katib/mnist_with_summary.py
- examples/katib/pytorch_job_mnist.yaml
Example of Pytorch mnist job in Katib
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pytorch-operator/112)
> Pytorch Katib example

- scripts/create-cluster.sh
K8s cluster 1.9 is no more supported in us-east1-d zone which is used for ci tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pytorch-operator/113)
> Update k8s cluster version to 1.10

- pkg/controller.v1beta1/pytorch/controller.go
- pkg/controller.v1beta1/pytorch/pod.go
New master role label is set in the pod which acts as master of the job. In katib, this label is useful to track the master who is responsible for logging.
Sets new label 'pytorch_job_role':'master' to the master pod 
This label is added for consistency with TFJob
Related: https://github.com/kubeflow/katib/issues/294
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pytorch-operator/116)
> Add master role label for PyTorchJob

- pkg/controller.v1beta1/pytorch/controller.go
- pkg/controller.v1beta1/pytorch/informer.go
- pkg/controller.v1beta1/pytorch/job.go
- pkg/controller.v2/pytorch/controller.go
- pkg/controller.v2/pytorch/informer.go
- pkg/controller.v2/pytorch/job.go
Minor fixes ported from https://github.com/kubeflow/tf-operator/pull/890
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pytorch-operator/115)
> Minor fixes

- pkg/controller.v1beta1/pytorch/status.go
- pkg/controller.v2/pytorch/status.go
GetCondition func should match the argument condition type
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pytorch-operator/114)
> GetCondition func fix

- build_image.sh
- scripts/build.sh
Updated all gcloud container builds calls to use gcloud builds as per [release notes](https://cloud.google.com/cloud-build/release-notes#july_24_2018) of `gcloud`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pytorch-operator/121)
> Updated gcloud build related code.

- examples/katib/Dockerfile
- examples/katib/dist_mnist_with_summary.py
- examples/katib/pytorch_job_mnist.yaml
For Katib, this PR adds a distributed mnist example that emits metrics
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pytorch-operator/118)
> Adding distributed mnist example with summaries

- README.md
- pkg/common/util/v1beta1/testutil/util.go
- pkg/common/util/v1beta2/testutil/util.go
- pkg/controller.v1beta1/pytorch/controller.go
- pkg/controller.v1beta1/pytorch/controller_test.go
- pkg/controller.v1beta2/pytorch/controller.go
- pkg/controller.v1beta2/pytorch/controller_test.go
- test/e2e/v1beta1/cleanpolicy_all.go
Fixes: #140 
All labels are renamed to use hyphens instead of underscores.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pytorch-operator/146)
> Renaming labels to consistent format

- cmd/pytorch-operator.v1beta2/app/server.go
- pkg/common/util/v1beta2/unstructured/informer.go
CRD client requires cluster scope access. Hence it is removed. Instead, error is checked for List API access.
Fixes: #144
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pytorch-operator/148)
> Remove usage of crd client

- Dockerfile
Secure base image is kept same as in tf-operator 
Related: https://github.com/kubeflow/tf-operator/pull/962
Fixes: #152
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pytorch-operator/153)
> Adding cleaner base image for operator builds 

- scripts/v1/run-cleanpodpolicy-all.sh
- scripts/v1/run-defaults.sh
- test/e2e/v1/cleanpolicy_all.go
- test/e2e/v1/defaults.go
- test/workflows/components/workflows.libsonnet
Tests for v1 api are added while v1beta1 tests are removed.
> Adding tests for operator v1 api

- cmd/pytorch-operator.v1/app/options/options.go
- cmd/pytorch-operator.v1/app/server.go
Related: https://github.com/kubeflow/tf-operator/pull/1013
> Making ResyncPeriod configurable

- pkg/controller.v1/pytorch/status.go
- pkg/controller.v1beta2/pytorch/status.go
Related: https://github.com/kubeflow/tf-operator/pull/1022
> Skip condition update when succeeded

- pkg/controller.v1/pytorch/status.go
- pkg/controller.v1beta2/pytorch/status.go
Start timestamp is set when job is created.
Related: https://github.com/kubeflow/tf-operator/pull/1001
> Set start timestamp

- README.md
- developer_guide.md
- examples/crd/crd-v1.yaml
This PR adds a developer guide similar to the one in [tensorflow operator](https://github.com/kubeflow/tf-operator/blob/master/developer_guide.md).
> Adds developer guide and sample CRD for v1

- scripts/create-cluster.sh
- scripts/setup-kubeflow.sh
- submit_release_job.sh
- test/workflows/app.yaml
- test/workflows/components/workflows.libsonnet
- test/workflows/environments/test/params.libsonnet
#188 is duplicated because CI tests need upgrade in k8s cluster version. In addition to earlier PR changes, cluster version is upgraded to 1.12
/cc @kunmingg
> update release script; fix post submit 

- cmd/pytorch-operator.v1/app/server.go
CoreV1 scheme is added as in v1beta2 version https://github.com/kubeflow/pytorch-operator/blob/master/cmd/pytorch-operator.v1beta2/app/server.go#L127
> Minor fix to add CoreV1 to scheme

- cmd/pytorch-operator.v1/app/options/options.go
- cmd/pytorch-operator.v1beta2/app/options/options.go
Signed-off-by: yeya24 <yb532204897@gmail.com>
Enable defining kubeconfig path in flag.
Mirror PR: https://github.com/kubeflow/tf-operator/pull/1049
> add kubeconfig flag

- pkg/controller.v1/pytorch/job.go
- pkg/controller.v1beta2/pytorch/job.go
We are using common.CleanPodPolicy now in pytorchjob, and if users set the policy to running, we will delete all pods and services. I think the behaviour is not consistent with tfjob. In pytorchjob, maybe we could support running, which does not delete anything just like None, to be user-friendly.
WDYT @johnugeorge 
One of our users does not know we do not support running, and use it. Then he found that the pods are deleted although they are not running
> feat: Support running although it is uesless

- .gcloudignore
- Dockerfile
- scripts/build.sh
Use multi-build to build pytorch-operator image.
See detail: #195
> Use multi-build to build pytorch-operator image

- pkg/common/util/v1/testutil/job.go
- pkg/common/util/v1beta2/testutil/job.go
When creating a pytorchjob object for testing, the default values should
also be filled in using the same defaulter function in the scheme.
> Set pytorchjob defaults in test utils

- cmd/pytorch-operator.v1/app/options/options.go
- cmd/pytorch-operator.v1/app/server.go
- cmd/pytorch-operator.v1beta2/app/options/options.go
- cmd/pytorch-operator.v1beta2/app/server.go
This PR improves the client performance when creating lots of jobs at the same time.
See: kubeflow/tf-operator#1063
> Add qps and burst options

- pkg/common/config/config.go
PytorchJob workers' initContainer always try to check if master pod is up by `nslookup` command, however nslookup in default image `busybox:1.31.0` version seems too old that it cannot work well, its exit code is always 1 for ppc64le arch even it can parse master service dns, and for amd64, it cannot work steadily as below, when I change the image to `alpine:3.10`, both on amd64 and ppc64le, it works well
```
/ # nslookup katib-suggestion-hyperband
Server:         10.0.0.10
Address:        10.0.0.10:53
Name:   katib-suggestion-hyperband.kubeflow.svc.cluster.local
Address: 10.0.223.142
*** Can't find katib-suggestion-hyperband.svc.cluster.local: No answer
*** Can't find katib-suggestion-hyperband.cluster.local: No answer
*** Can't find katib-suggestion-hyperband.fyre.ibm.com: No answer
*** …
```
> Fix nslookup cannot work well in initContainerTemplate

- pkg/controller.v1/pytorch/controller.go
Like the PR in the tf-operator  https://github.com/kubeflow/tf-operator/pull/1111
This PR reorders the checking process so if the job has terminated(Succeed, Failed), it will return instead of further reconcile.
The ExceedsBackOffLimit and ActiveDeadLineSeconds should be handle afterward.
> fix the reconcile flow

- sdk/python/README.md
- sdk/python/docs/PyTorchJobClient.md
- sdk/python/examples/kubeflow-pytorchjob-sdk.ipynb
- sdk/python/kubeflow/pytorchjob/api/py_torch_job_client.py
- sdk/python/kubeflow/pytorchjob/constants/constants.py
- sdk/python/kubeflow/pytorchjob/utils/utils.py
- sdk/python/setup.py
- sdk/python/test/test_e2e.py
`kubeflow-pytorchjob` SDK supports getting training process or logs and pod name of the PyTorchJob. 
Related with https://github.com/kubeflow/tf-operator/issues/1129
> SDK supports getting PyTorchJob training process or logs

- examples/pytorch_cuda_docker/Dockerfile
Added The Pytorch GPU Docker under the appropriate folder.
Pytorch Docker is not working so added the pytorch docker capable of taking GPU as resource
> Added The Pytorch GPU Docker under the appropriate folder

- sdk/python/requirements.txt
- sdk/python/setup.py
There is a problem in new kubenertes Client v11.0.0: https://github.com/kubernetes-client/python/issues/1112
The PR is going to pin the kubenertes Client to 10.0.1 to avoid the issue. Thanks
> pin kubenertes client version to work around a bug

- examples/mnist/Dockerfile
- manifests/rbac.yaml
- pkg/common/config/config.go
Hi, I'd like to propose these three changes to get pytorch operator and example working on OpenShift
The Dockerfile change is required because containers run as non-root user in OpenShift and the mnist.py needs to create some directories and files
The config.go is necessary because OpenShift has some minimial values set so we need to get over those values.
The rbac.yaml adds a missing resource which is needed in OpenShift to successfully operate the CRs
> Fix minor OpenShift issues - resource requests, Dockerfile

- hack/python-sdk/gen-sdk.sh
The PR is going to fix one out-of-date link, see more in https://github.com/kubeflow/tf-operator/issues/1166
> Update swagger-codegen-cli URL

- examples/mnist/Dockerfile-mpi
(curl -o -O) it's not work when I built image of mpi at aliyun
> fix Dockerfile-mpi download miniconda.sh

- examples/mnist/README.md
- examples/mnist/v1/pytorch_job_mnist_gloo.yaml
- examples/mnist/v1/pytorch_job_mnist_mpi.yaml
- examples/mnist/v1/pytorch_job_mnist_nccl.yaml
Supports https://github.com/kubeflow/website/issues/2011
> Adds notes and example annotation for pytorch job

- go.sum
- pkg/controller.v1/pytorch/job.go
- pkg/controller.v1/pytorch/job_test.go
- pkg/controller.v1/pytorch/pod_test.go
Related: https://github.com/kubeflow/pytorch-operator/issues/292.
I was able to run unit test locally after these changes .
1. I changed `expectedServiceDeletions` from 0 to 1. Here: https://github.com/kubeflow/pytorch-operator/blob/master/pkg/controller.v1/pytorch/job.go#L163-L171, we don't check that `job.Spec.CleanPodPolicy == common.CleanPodPolicyRunning` before deleting services. 
@jiaqianjing is that correct behaviour? In TF operator we have one loop for services and pods: https://github.com/kubeflow/tf-operator/blob/master/pkg/controller.v1/tensorflow/job.go#L162-L172, but in PyTorch operator we analyse services and pods in the different loops.
2. To fix this error: `Fail in goroutine after TestCopyLabelsAndAnnotation has completed`, I changed run test controller, like here: …
> Fix Unit Tests

- OWNERS
I would like to add myself to approvers. I am working on `kubeflow/common` and other operators a lot and I am pretty familiar with the code base. Currently I am working on pytorch test infra migration and pytorch kubeflow/common migration. Hope to gain access to iterate faster. 
Not that many PRs against PyTorch but I would like to contribute more. 
https://github.com/kubeflow/pytorch-operator/pulls/Jeffwan
/cc @johnugeorge  @gaocegege
> Add Jeffwan@ to OWNERS

- OWNERS
I moved myself from reviews to approvers list to help with `/approve` current PRs.
As well, alphabetise the list.
/assign @johnugeorge @gaocegege @Jeffwan
> Add @andreyvelich to approvers

- manifests/deployment.yaml
fix [issue294](https://github.com/kubeflow/pytorch-operator/issues/294)
> update pytorch-operator deployment manifests file

- manifests/pytorch-job-crds/base/crd.yaml
- manifests/pytorch-job-crds/base/kustomization.yaml
- manifests/pytorch-job-crds/overlays/application/application.yaml
- manifests/pytorch-job-crds/overlays/application/kustomization.yaml
- manifests/pytorch-operator/base/cluster-role-binding.yaml
- manifests/pytorch-operator/base/cluster-role.yaml
- manifests/pytorch-operator/base/deployment.yaml
- manifests/pytorch-operator/base/kustomization.yaml
- manifests/pytorch-operator/base/params.env
- manifests/pytorch-operator/base/service-account.yaml
- manifests/pytorch-operator/base/service.yaml
- manifests/pytorch-operator/overlays/application/application.yaml
- manifests/pytorch-operator/overlays/application/kustomization.yaml
Resolves: https://github.com/kubeflow/pytorch-operator/issues/318
Umbrella issue: https://github.com/kubeflow/manifests/issues/1740
As part of the work of wg-manifests for 1.3
(https://github.com/kubeflow/manifests/issues/1735), we are moving manifests
development in upstream repos. This gives the application developers full
ownership of their manifests, tracked in a single place.
This PR copies the manifests for application `PyTorch Operator`
from path `apps/pytorch-job/upstream` of kubeflow/manifests to path
`manifests` of the upstream repo (https://github.com/kubeflow/pytorch-operator).
cc @kubeflow/wg-training-leads
> PyTorch Operator: Move manifests development upstream

- scripts/v1/run-cleanpodpolicy-all.sh
- scripts/v1/run-defaults.sh
As mnist dataset server is not stable, pytorch-operator CI job is affected which blocks PR merge. I will temporarily disable it and bring it back later with the improvement
See following links for more details
https://discuss.pytorch.org/t/mnist-server-down/114433
https://github.com/pytorch/vision/issues/3554
Signed-off-by: Jiaxin Shan <seedjeffwan@gmail.com>
> Temporarily disable mnist test case

- examples/mnist/mnist.py
Follow @andreyvelich suggestion and this works well with existing sample code
> Change mnist example to use FashionMNIST

- pkg/controller.v1/pytorch/controller.go
- pkg/controller.v1/pytorch/job.go
- pkg/controller.v1/pytorch/status.go
This PR adds the job's namespace as a label to Prometheus metrics reported by the operator, making it possible to filter metrics per-namespaces as opposed to global counters.
Similar PR for TFJob operator: https://github.com/kubeflow/tf-operator/pull/1283
> Add job namespace to `pytorch_operator_jobs_*` counters

- pkg/controller.v1/pytorch/controller.go
Fixes `Invalid Pointer` error when `PytorchJob` is deleted.
Based on the fix from `tf-operator`: https://github.com/kubeflow/tf-operator/pull/1285
> Fix 'Invalid Pointer' error when PytorchJob is deleted
